packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - sharp

catalog:
  typescript: ^5.9
  "@types/node": ^22
  next: ^16.0

catalogs:
  react:
    react: ^19.2.0
    react-dom: ^19.2.0
    "@types/react": ^19.2.0
    "@types/react-dom": ^19.2.0

  tailwind:
    tailwindcss: ^4.1.11
    postcss: ^8
    "@tailwindcss/postcss": ^4.1.11
