packages:
  - apps/*
  - packages/*

ignoredBuiltDependencies:
  - sharp

catalog:
  typescript: ^5.9
  "@types/node": ^22
  next: ^16.0.10

catalogs:
  react:
    react: ^19.2.3
    react-dom: ^19.2.3
    "@types/react": ^19.2.3
    "@types/react-dom": ^19.2.3

  tailwind:
    tailwindcss: ^4.1.18
    postcss: ^8
    "@tailwindcss/postcss": ^4.1.18
