services:
  postgres:
    image: postgres:16-alpine
    container_name: harmony_postgres
    environment:
      - POSTGRES_USER=harmony
      - POSTGRES_PASSWORD=harmony
      - POSTGRES_DB=harmony
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
