/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as AppPackageIdRouteImport } from './routes/app/$packageId'
import { Route as AppPackageIdAlbumsRouteImport } from './routes/app/$packageId/albums'
import { Route as AppPackageIdArtistsRouteImport } from './routes/app/$packageId/artists'
import { Route as AppPackageIdDiscoveriesRouteImport } from './routes/app/$packageId/discoveries'
import { Route as AppPackageIdListeningRouteImport } from './routes/app/$packageId/listening'
import { Route as AppPackageIdPackageRouteImport } from './routes/app/$packageId/package'
import { Route as AppPackageIdTracksRouteImport } from './routes/app/$packageId/tracks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPackageIdRoute = AppPackageIdRouteImport.update({
  id: '/app/$packageId',
  path: '/app/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPackageIdAlbumsRoute = AppPackageIdAlbumsRouteImport.update({
  id: '/albums',
  path: '/albums',
  getParentRoute: () => AppPackageIdRoute,
} as any)
const AppPackageIdArtistsRoute = AppPackageIdArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => AppPackageIdRoute,
} as any)
const AppPackageIdDiscoveriesRoute = AppPackageIdDiscoveriesRouteImport.update({
  id: '/discoveries',
  path: '/discoveries',
  getParentRoute: () => AppPackageIdRoute,
} as any)
const AppPackageIdListeningRoute = AppPackageIdListeningRouteImport.update({
  id: '/listening',
  path: '/listening',
  getParentRoute: () => AppPackageIdRoute,
} as any)
const AppPackageIdPackageRoute = AppPackageIdPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => AppPackageIdRoute,
} as any)
const AppPackageIdTracksRoute = AppPackageIdTracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => AppPackageIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/app/$packageId': typeof AppPackageIdRouteWithChildren
  '/app/$packageId/albums': typeof AppPackageIdAlbumsRoute
  '/app/$packageId/artists': typeof AppPackageIdArtistsRoute
  '/app/$packageId/discoveries': typeof AppPackageIdDiscoveriesRoute
  '/app/$packageId/listening': typeof AppPackageIdListeningRoute
  '/app/$packageId/package': typeof AppPackageIdPackageRoute
  '/app/$packageId/tracks': typeof AppPackageIdTracksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/app/$packageId': typeof AppPackageIdRouteWithChildren
  '/app/$packageId/albums': typeof AppPackageIdAlbumsRoute
  '/app/$packageId/artists': typeof AppPackageIdArtistsRoute
  '/app/$packageId/discoveries': typeof AppPackageIdDiscoveriesRoute
  '/app/$packageId/listening': typeof AppPackageIdListeningRoute
  '/app/$packageId/package': typeof AppPackageIdPackageRoute
  '/app/$packageId/tracks': typeof AppPackageIdTracksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/upload': typeof UploadRoute
  '/app/$packageId': typeof AppPackageIdRouteWithChildren
  '/app/$packageId/albums': typeof AppPackageIdAlbumsRoute
  '/app/$packageId/artists': typeof AppPackageIdArtistsRoute
  '/app/$packageId/discoveries': typeof AppPackageIdDiscoveriesRoute
  '/app/$packageId/listening': typeof AppPackageIdListeningRoute
  '/app/$packageId/package': typeof AppPackageIdPackageRoute
  '/app/$packageId/tracks': typeof AppPackageIdTracksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/upload'
    | '/app/$packageId'
    | '/app/$packageId/albums'
    | '/app/$packageId/artists'
    | '/app/$packageId/discoveries'
    | '/app/$packageId/listening'
    | '/app/$packageId/package'
    | '/app/$packageId/tracks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/upload'
    | '/app/$packageId'
    | '/app/$packageId/albums'
    | '/app/$packageId/artists'
    | '/app/$packageId/discoveries'
    | '/app/$packageId/listening'
    | '/app/$packageId/package'
    | '/app/$packageId/tracks'
  id:
    | '__root__'
    | '/'
    | '/upload'
    | '/app/$packageId'
    | '/app/$packageId/albums'
    | '/app/$packageId/artists'
    | '/app/$packageId/discoveries'
    | '/app/$packageId/listening'
    | '/app/$packageId/package'
    | '/app/$packageId/tracks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UploadRoute: typeof UploadRoute
  AppPackageIdRoute: typeof AppPackageIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$packageId': {
      id: '/app/$packageId'
      path: '/app/$packageId'
      fullPath: '/app/$packageId'
      preLoaderRoute: typeof AppPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$packageId/albums': {
      id: '/app/$packageId/albums'
      path: '/albums'
      fullPath: '/app/$packageId/albums'
      preLoaderRoute: typeof AppPackageIdAlbumsRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
    '/app/$packageId/artists': {
      id: '/app/$packageId/artists'
      path: '/artists'
      fullPath: '/app/$packageId/artists'
      preLoaderRoute: typeof AppPackageIdArtistsRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
    '/app/$packageId/discoveries': {
      id: '/app/$packageId/discoveries'
      path: '/discoveries'
      fullPath: '/app/$packageId/discoveries'
      preLoaderRoute: typeof AppPackageIdDiscoveriesRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
    '/app/$packageId/listening': {
      id: '/app/$packageId/listening'
      path: '/listening'
      fullPath: '/app/$packageId/listening'
      preLoaderRoute: typeof AppPackageIdListeningRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
    '/app/$packageId/package': {
      id: '/app/$packageId/package'
      path: '/package'
      fullPath: '/app/$packageId/package'
      preLoaderRoute: typeof AppPackageIdPackageRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
    '/app/$packageId/tracks': {
      id: '/app/$packageId/tracks'
      path: '/tracks'
      fullPath: '/app/$packageId/tracks'
      preLoaderRoute: typeof AppPackageIdTracksRouteImport
      parentRoute: typeof AppPackageIdRoute
    }
  }
}

interface AppPackageIdRouteChildren {
  AppPackageIdAlbumsRoute: typeof AppPackageIdAlbumsRoute
  AppPackageIdArtistsRoute: typeof AppPackageIdArtistsRoute
  AppPackageIdDiscoveriesRoute: typeof AppPackageIdDiscoveriesRoute
  AppPackageIdListeningRoute: typeof AppPackageIdListeningRoute
  AppPackageIdPackageRoute: typeof AppPackageIdPackageRoute
  AppPackageIdTracksRoute: typeof AppPackageIdTracksRoute
}

const AppPackageIdRouteChildren: AppPackageIdRouteChildren = {
  AppPackageIdAlbumsRoute: AppPackageIdAlbumsRoute,
  AppPackageIdArtistsRoute: AppPackageIdArtistsRoute,
  AppPackageIdDiscoveriesRoute: AppPackageIdDiscoveriesRoute,
  AppPackageIdListeningRoute: AppPackageIdListeningRoute,
  AppPackageIdPackageRoute: AppPackageIdPackageRoute,
  AppPackageIdTracksRoute: AppPackageIdTracksRoute,
}

const AppPackageIdRouteWithChildren = AppPackageIdRoute._addFileChildren(
  AppPackageIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UploadRoute: UploadRoute,
  AppPackageIdRoute: AppPackageIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
