[package]
name = "harmony_processing"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
rayon = "1.10.0"
regex = "1.10.4"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
simd-json = "0.13.10"
thiserror = "1.0.61"
zip = "1.3.0"
