/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AlbumArtistSchema extends BaseModel {
  static $columns = ['albumId', 'artistId'] as const
  $columns = AlbumArtistSchema.$columns
  @column()
  declare albumId: number
  @column()
  declare artistId: number
}

export class AlbumSchema extends BaseModel {
  static $columns = ['id', 'type', 'name', 'image', 'totalTracks', 'releaseDate', 'externalId'] as const
  $columns = AlbumSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare type: any
  @column()
  declare name: string
  @column()
  declare image: string | null
  @column()
  declare totalTracks: number
  @column()
  declare releaseDate: string
  @column()
  declare externalId: string
}

export class ArtistSchema extends BaseModel {
  static $columns = ['id', 'name', 'image', 'externalId'] as const
  $columns = ArtistSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare image: string | null
  @column()
  declare externalId: string
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class InteractionSchema extends BaseModel {
  static $columns = ['packageId', 'trackId', 'timestamp', 'msPlayed', 'platform', 'reasonStart', 'reasonEnd', 'shuffle', 'skipped', 'offline'] as const
  $columns = InteractionSchema.$columns
  @column()
  declare packageId: string
  @column()
  declare trackId: number
  @column.dateTime()
  declare timestamp: DateTime
  @column()
  declare msPlayed: number
  @column()
  declare platform: string | null
  @column()
  declare reasonStart: string | null
  @column()
  declare reasonEnd: string | null
  @column()
  declare shuffle: boolean | null
  @column()
  declare skipped: boolean | null
  @column()
  declare offline: boolean | null
}

export class PackageSchema extends BaseModel {
  static $columns = ['id', 'fileName', 'fileSize', 'status', 'createdAt'] as const
  $columns = PackageSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare fileName: string
  @column()
  declare fileSize: number
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
}

export class TrackArtistSchema extends BaseModel {
  static $columns = ['trackId', 'artistId'] as const
  $columns = TrackArtistSchema.$columns
  @column()
  declare trackId: number
  @column()
  declare artistId: number
}

export class TrackSchema extends BaseModel {
  static $columns = ['id', 'name', 'msDuration', 'trackNumber', 'albumId', 'externalId'] as const
  $columns = TrackSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare msDuration: number | null
  @column()
  declare trackNumber: number | null
  @column()
  declare albumId: number
  @column()
  declare externalId: string
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
